# Generated by Django 3.2.3 on 2021-07-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_galary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='galary',
            new_name='Gallery',
        ),
    ]
