# Generated by Django 3.2.3 on 2021-07-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_galary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spic', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='galary',
        ),
    ]
