# Generated by Django 3.2.3 on 2021-07-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210725_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField(max_length=200)),
                ('pdesc', models.TextField(max_length=20000)),
                ('ppic', models.TextField(null=True)),
                ('pprice', models.IntegerField()),
            ],
        ),
    ]
