# Generated by Django 3.2.3 on 2021-07-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_post_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctvpic', models.TextField(null=True)),
                ('cctvname', models.TextField(null=True)),
                ('cctvdesc', models.TextField(null=True)),
                ('cctvprice', models.TextField(null=True)),
            ],
        ),
    ]
