# Generated by Django 3.2.3 on 2021-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_cctv'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusname', models.TextField(null=True)),
                ('cuspic', models.TextField(null=True)),
                ('cusreview', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scustomer', models.IntegerField()),
                ('ssells', models.IntegerField()),
                ('sproducts', models.IntegerField()),
                ('smembers', models.IntegerField()),
            ],
        ),
    ]
